-- =========================================================
-- TB_AIRLINE: 운영중 + IATA 2자리 전체(국토교통부_세계항공사_코드_20241231)
-- - 기준 CSV: 국토교통부_세계항공사_코드_20241231 (1).csv
-- - 처리: 운영중 AND IATA 길이=2, IATA 중복 제거(첫 행 유지)
-- - COUNTRY/URL/TEAM: CSV에 없음 → COUNTRY='UNKNOWN', URL/TEAM=NULL
-- =========================================================
-- 시퀀스 별칭(동의어) 생성


ALTER TABLE TB_AIRLINE MODIFY AIRLINE_URL NULL;

-- ===== MERGE BATCH 1/5 =====
MERGE INTO TB_AIRLINE t
USING (
    SELECT '0A' IATA, '아스타 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '0B' IATA, 'BBN 인도네시아 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '0V' IATA, '베트남 항공 서비스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '1I' IATA, '넷제트' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '1X' IATA, '브랜슨 에어 익스프레스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '2A' IATA, '에어 아스트라' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '2C' IATA, 'CMA CGM 화물항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '2D' IATA, '이스턴 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '2E' IATA, '스모키베이 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '2F' IATA, '아줄 코넥타' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '2G' IATA, '앙공라 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '2I' IATA, '21 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '2J' IATA, '에어 부르키나' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '2K' IATA, '아비앙카 에콰도르' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '2L' IATA, '헬베틱 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '2M' IATA, '마야 아일랜드 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '2N' IATA, '스마트링스 항공 몰타' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '2P' IATA, 'PAL 익스프레스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '2Q' IATA, '에어 카고캐리어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '2R' IATA, '선라이트 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '2S' IATA, '사우스윈드 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '2T' IATA, '버뮤다항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '2U' IATA, '플라이 키바' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '2W' IATA, '월드투플라이' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '2Y' IATA, '마이 인도 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '2Z' IATA, 'VOEPASS 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '3C' IATA, '에어 차트마스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '3E' IATA, '엘렉트라 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '3F' IATA, '플라이원 아르메니아' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '3G' IATA, '월드 카고 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '3H' IATA, '에어 인뉴이트' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '3J' IATA, '주바 항공 소말리아' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '3K' IATA, '제트스타 아시아' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '3L' IATA, '에어 아라비아 아부다비' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '3M' IATA, '실버항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '3N' IATA, '에어 우르가' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '3O' IATA, '에어 아라비아 모로코' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '3P' IATA, '월드투플라이 포르투갈' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '3Q' IATA, '로얄 잠비아 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '3R' IATA, '디비 디비 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '3S' IATA, '에어로로직' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '3T' IATA, '타르코 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '3U' IATA, '쓰촨 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '3V' IATA, 'ASL 벨기에 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '3W' IATA, '말라이 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '3X' IATA, '프리미어 트랜스 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '3Z' IATA, '스마트윙스 폴란드' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '4A' IATA, 'ATSA 페루' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '4B' IATA, '아비아스타-TU' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '4C' IATA, '라탐 항공 콜롬비아' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '4E' IATA, '스타보에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '4F' IATA, '프리덤 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '4K' IATA, '아스카리 에비에이션' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '4L' IATA, 'LAS 화물 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '4M' IATA, '마비곡 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '4N' IATA, '에어 노스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '4O' IATA, '에어 몬테네그로' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '4P' IATA, '리저널 스카이' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '4R' IATA, '스타이스트 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '4S' IATA, '홍해 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '4U' IATA, '제제트 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '4W' IATA, '얼라이드 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '4X' IATA, '아비온 익스프레스 몰타' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '4Y' IATA, '에어버스 국제운송' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '4Z' IATA, '에어링크 남아공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '5A' IATA, '알파인 에어 익스프레스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '5C' IATA, '챌린지 항공 IL' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '5D' IATA, '아에로멕시코 커넥트' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '5F' IATA, '플라이 원' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '5G' IATA, '시라크 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '5J' IATA, '세부 퍼시픽 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '5K' IATA, '하이 플라이' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '5M' IATA, '플라이 몬세라트' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '5N' IATA, '스마타비아' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '5O' IATA, 'ASL 프랑스 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '5P' IATA, '파노라마 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '5Q' IATA, '홀리데이 유럽' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '5R' IATA, '루타카 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '5S' IATA, '글로벌 항공 운송' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '5T' IATA, '캐나다 북부 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '5U' IATA, '과테말라 항공 운송' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '5V' IATA, '에버츠 항공 화물' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '5W' IATA, '위즈 에어 아부다비' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '5X' IATA, 'UPS' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '5Y' IATA, '아틀라스 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '5Z' IATA, '셈에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '6A' IATA, '아르메니아 에어웨이' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '6B' IATA, 'TUI 플라이 노르딕' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '6C' IATA, '에어 티모르' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '6D' IATA, '스마트윙스 슬로바키아' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '6E' IATA, '인디고 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '6G' IATA, '고투스카이' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '6I' IATA, '에어 알시' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '6J' IATA, '솔라시드 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '6L' IATA, '악락 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '6M' IATA, '막시무스 에어카고' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '6O' IATA, '이베로젯 포르투갈' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '6P' IATA, '프라단 에어 익스프레스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '6Q' IATA, '참윙스 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '6R' IATA, '아에로 유니온' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '6U' IATA, '유니크 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '6V' IATA, 'MRK 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '6Y' IATA, '스마트링스 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '7A' IATA, '익스프레스 에어 카고' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '7B' IATA, '에어보르네오' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '7C' IATA, '코인 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '7D' IATA, 'MGC 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '7E' IATA, '실트 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '7G' IATA, '스타플라이어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '7H' IATA, '뉴퍼시픽 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '7I' IATA, '에어 리비아' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '7L' IATA, '에어로카리비엔' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '7M' IATA, 'MAP 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '7O' IATA, '스마트윙스 헝가리' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '7P' IATA, '에어 파나마' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '7R' IATA, '루스라인' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '7S' IATA, '라이언 에어서비스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '7T' IATA, 'DHL 에콰도르' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '7V' IATA, '페데랄 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '7W' IATA, '윈드로즈 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '7Y' IATA, '만야다나폰 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '7Z' IATA, 'Z 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '8B' IATA, '트랜스누사 항공 서비스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '8C' IATA, '에어 트랜스포트 인터내셔널' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '8D' IATA, 'FITS 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '8E' IATA, '베링항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '8F' IATA, '카딕 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '8G' IATA, '에어로 딜리' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '8H' IATA, 'BH 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '8J' IATA, '에코젯' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '8K' IATA, '에바스 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '8L' IATA, '럭키 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '8M' IATA, '미얀마 국제항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '8N' IATA, '리저널 항공 서비스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '8P' IATA, '퍼시픽 코스탈 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '8R' IATA, '아멜리아항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '8S' IATA, '갈리스테어 몰타' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '8T' IATA, '에어 틴디' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '8U' IATA, '아프리키야 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '8V' IATA, '아스트랄 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '8W' IATA, '플라이 올웨이즈' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '8Y' IATA, '팬퍼시픽 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '8Z' IATA, '에어 콩고' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '9A' IATA, 'GCA 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '9C' IATA, '춘추 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '9D' IATA, '징기스칸 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '9E' IATA, '엔더버 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '9H' IATA, '에어 장안' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '9I' IATA, '얼라이언스 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '9K' IATA, '케이프 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '9M' IATA, '센터럴 마운틴에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '9N' IATA, '트로픽 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '9P' IATA, '플라이 진나' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '9Q' IATA, '카이코스 익스프레스 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '9R' IATA, '사테나 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '9S' IATA, '에어 사마르칸트' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '9T' IATA, '에어 엑트' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '9V' IATA, '아비어 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '9X' IATA, '서던 익스프레스 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT '9Y' IATA, '내셔널 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'A0' IATA, '아비앙카 아르헨티나' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'A2' IATA, '애니마윙스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'A3' IATA, '에게안 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'A5' IATA, 'HOP! 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'A6' IATA, '에어 트래블' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'A7' IATA, '어썸 카고' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'A8' IATA, '아메리라이트' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'A9' IATA, '조지아 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'AA' IATA, '아메리칸 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'AC' IATA, '에어 캐나다' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'AD' IATA, '아줄 브라질' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'AE' IATA, '만다린 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'AF' IATA, '에어 프랑스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'AG' IATA, '아루바 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'AH' IATA, '에어 알제리' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'AI' IATA, '에어 인도' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'AJ' IATA, '아즈텍 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'AK' IATA, '에어아시아' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'AM' IATA, '아에로 멕시코' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'AN' IATA, '어드밴스드 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'AO' IATA, '에어 후한' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'AP' IATA, '알바스타' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'AQ' IATA, '9 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'AR' IATA, '아르헨티나 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'AS' IATA, '알래스카 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'AT' IATA, '로얄 모로코 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'AV' IATA, '아비앙카 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'AW' IATA, '아프리카 월드 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'AY' IATA, '핀 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'AZ' IATA, 'ITA항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'B0' IATA, '라 콤페니' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'B2' IATA, '벨라비아 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'B3' IATA, '부탄 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'B4' IATA, '비온드 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'B5' IATA, 'BBN 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'B6' IATA, '제트블루 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'B7' IATA, '유니 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'B8' IATA, '에리트레아 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'B9' IATA, '이란 에어 투어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'BA' IATA, '영국 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
) s
ON (t.AIRLINE_IATA_CODE = s.IATA)
WHEN NOT MATCHED THEN
  INSERT (
    AIRLINE_ID,
    AIRLINE_AIRLINE_NAME,
    AIRLINE_IATA_CODE,
    AIRLINE_COUNTRY,
    AIRLINE_URL,
    AIRPORT_TEAM
  )
  VALUES (
    TB_AIRLINE_SEQ.NEXTVAL,
    s.NAME,
    s.IATA,
    s.COUNTRY,
    s.URL,
    s.TEAM
  );

-- ===== MERGE BATCH 2/5 =====
MERGE INTO TB_AIRLINE t
USING (
    SELECT 'BB' IATA, '시본 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'BC' IATA, '스카이마크 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'BD' IATA, '버짓 라인' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'BF' IATA, '프렌치 비' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'BG' IATA, '비만 방글라데시 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'BH' IATA, '비스밀라 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'BI' IATA, '로얄 브루나이 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'BJ' IATA, '누벨레어 튀니지' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'BK' IATA, '오캐이 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'BL' IATA, '퍼시픽 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'BM' IATA, '메드스키 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'BN' IATA, '럭스윙' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'BP' IATA, '에어 보츠와나' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'BQ' IATA, '스카이 알프스 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'BR' IATA, '에바 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'BS' IATA, '영국 국제 헬리콥터' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'BT' IATA, '에어발틱' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'BU' IATA, '아프리카 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'BV' IATA, '토키 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'BW' IATA, '카리브 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'BX' IATA, '에어 부산' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'BY' IATA, 'TUI 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'BZ' IATA, '블루다트 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'C0' IATA, 'FTL 에어라인즈' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'C2' IATA, '세이바 인터콘티넨탈' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'C3' IATA, '카고 쓰리' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'C4' IATA, '콘퀘스트 항공 화물' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'C5' IATA, '커뮤트 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'C6' IATA, '마이 프라이터 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'C7' IATA, '시나몬 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'C8' IATA, '카고룩스 이탈리아' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'C9' IATA, '크로노스 항공 베냉' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'CA' IATA, '에어 중국' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'CC' IATA, '에어 애틀랜타 아이슬란드' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'CD' IATA, '코렌돈 네덜란드 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'CE' IATA, '샬레어 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'CF' IATA, '차이나 포스탈 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'CG' IATA, 'PNG 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'CH' IATA, '베미지 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'CI' IATA, '중화 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'CJ' IATA, 'BA 시티플라이어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'CK' IATA, '중국 화물 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'CL' IATA, '루프트한자 시티라인' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'CM' IATA, '코파 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'CN' IATA, '그랜드 차이나 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'CO' IATA, '중국 노스웨스턴 국제항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'CQ' IATA, '코스탈 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'CU' IATA, '쿠바 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'CV' IATA, '카고룩스 국제항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'CX' IATA, '캐세이퍼시픽 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'CY' IATA, '키프로스 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'CZ' IATA, '중국 남방 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'D0' IATA, 'DHL 에어 영국' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'D2' IATA, '세버스탈 에어컴퍼니' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'D3' IATA, '달로 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'D4' IATA, '지오스카이' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'D5' IATA, 'DHL 에어로 익스프레스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'D7' IATA, '에어아시아 엑스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'D8' IATA, '노르웨이 항공 스웨덴 AOC' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'DB' IATA, '말레스 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'DD' IATA, '녹 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'DE' IATA, '콘도르 플루그디엔스트' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'DF' IATA, '디어제트항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'DG' IATA, '세브고' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'DI' IATA, '마라부' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'DJ' IATA, '에어 지부티' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'DK' IATA, '선클래스 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'DL' IATA, '델타항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'DM' IATA, '아라젯' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'DN' IATA, '단에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'DO' IATA, '스카이하이 도미니카나' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'DP' IATA, '포베다 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'DQ' IATA, '알렉산드리아 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'DR' IATA, '수난 루이리 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'DS' IATA, '이지젯 스위스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'DT' IATA, 'TAAG 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'DV' IATA, '스캇 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'DX' IATA, 'DAT 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'DY' IATA, '노르웨이 항공 셔틀 AOC' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'DZ' IATA, '둥하이 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'E2' IATA, '에어하이파' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'E3' IATA, '프리마 항공 트라스포티 이탈리아니' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'E4' IATA, '아에로탁시 아베테' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'E5' IATA, '에어 아라비아 이집트' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'E6' IATA, '유로윙스 유럽 리미티드' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'E7' IATA, '이쿼플라이트' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'E9' IATA, '이베로젯' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'EA' IATA, '에메랄드항공 아일랜드' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'EB' IATA, '와모스 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'EC' IATA, '이지젯 유럽' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'ED' IATA, '에어익스플로어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'EF' IATA, '에어카리베 페루' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'EH' IATA, '아나 윙즈' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'EI' IATA, '에어링거스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'EJ' IATA, '뉴 잉글랜드 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'EK' IATA, '에미레이트 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'EL' IATA, '엘리항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'EN' IATA, '에어 돌로미티' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'EP' IATA, '이란 아세만항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'EQ' IATA, '플라이 앙골라' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'ER' IATA, '세린 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'ES' IATA, 'DHL 국제항공 ME' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'ET' IATA, '에메테베' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'EU' IATA, '청두 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'EW' IATA, '유로윙즈' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'EX' IATA, '리저널 익스프레스 아메리카' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'EY' IATA, '에티하드 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'EZ' IATA, '선에어 스칸디나비아' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'F0' IATA, '플라이 요르단' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'F2' IATA, '사파리 링크 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'F3' IATA, '플라이어딜' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'F4' IATA, '에어 플라맹고' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'F5' IATA, '에어로트렌스카고' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'F6' IATA, '플라이투스카이' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'F7' IATA, '아이플라이' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'F8' IATA, '플레어항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'F9' IATA, '프론티어 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'FA' IATA, '플라이사페어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'FB' IATA, '불가리아 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'FD' IATA, '타이 에어아시아' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'FE' IATA, '748 항공서비스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'FG' IATA, '아리아나 아프간 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'FH' IATA, '프리버드 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'FI' IATA, '아이슬란드 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'FJ' IATA, '피지 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'FK' IATA, '키와틴 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'FL' IATA, '플라이 릴리' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'FM' IATA, '상해 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'FN' IATA, '페스트젯 짐바브웨' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'FO' IATA, '플라이본디' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'FP' IATA, '플라이 펠리칸' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'FR' IATA, '라이언에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'FS' IATA, '에어 팔콘' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'FT' IATA, '플라이 이집트' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'FU' IATA, '푸저우 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'FV' IATA, '로시야 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'FW' IATA, '아이벡스 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'FX' IATA, '페덱스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'FY' IATA, '파이어플라이' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'FZ' IATA, '플라이두바이' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'G0' IATA, '알바트로스 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'G2' IATA, '걸리버 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'G3' IATA, '골 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'G4' IATA, '엘리지언트 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'G5' IATA, '중국 익스프레스 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'G6' IATA, '글로벌 크로싱 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'G7' IATA, '고젯 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'G9' IATA, '에어 아라비아' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'GA' IATA, '가루다 인도네시아 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'GB' IATA, 'ABX 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'GD' IATA, '에비에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'GE' IATA, '글로벌 항공 운영' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'GF' IATA, '걸프항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'GG' IATA, '스카이리스 카고' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'GH' IATA, '조지아 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'GI' IATA, '에어 센트럴' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'GJ' IATA, '룽 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'GK' IATA, '제트스타 일본' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'GL' IATA, '에어 그린란드' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'GM' IATA, '아시아 카고 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'GO' IATA, 'ULS 화물항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'GP' IATA, 'APG 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'GQ' IATA, '스카이 익스프레스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'GR' IATA, '오리니 에어서비스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'GS' IATA, '천진 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'GT' IATA, '에어 구이린' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'GU' IATA, '아비앙카 과테말라' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'GV' IATA, '그랜트 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'GW' IATA, '겟젯 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'GX' IATA, '광시 베이부 걸프 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'GY' IATA, '컬러풀 구이저우 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'GZ' IATA, '에어 라로통가' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'H2' IATA, '스카이 칠레 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'H3' IATA, '헬로젯' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'H4' IATA, '하이스카이 루마니아' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'H5' IATA, 'CM 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'H6' IATA, '유럽 항공 차터' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'H7' IATA, '이글 에어 우간다' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'H8' IATA, '스카이 페루' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'H9' IATA, '히말라야 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'HA' IATA, '하와이안 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'HB' IATA, '그레이터 베이 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'HC' IATA, '에어 세네갈' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'HD' IATA, '에어 두' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'HF' IATA, '에어 코트디부아르' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'HG' IATA, '하이버니언 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'HH' IATA, '카나트 샤크 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'HI' IATA, '필리핀 그랜드캐년 헬리콥터' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'HJ' IATA, '타즈만 카고 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'HK' IATA, '스키퍼스 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'HM' IATA, '에어 세이쉘' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'HN' IATA, '헤스톤 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'HO' IATA, '준야오 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'HP' IATA, '포풀에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'HQ' IATA, '컴퍼스 화물항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'HR' IATA, '한에어라인' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'HT' IATA, '에어 호라이즌' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'HU' IATA, '하이난 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'HV' IATA, '트랜스아비아' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'HW' IATA, '노스라이트 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
) s
ON (t.AIRLINE_IATA_CODE = s.IATA)
WHEN NOT MATCHED THEN
  INSERT (
    AIRLINE_ID,
    AIRLINE_AIRLINE_NAME,
    AIRLINE_IATA_CODE,
    AIRLINE_COUNTRY,
    AIRLINE_URL,
    AIRPORT_TEAM
  )
  VALUES (
    TB_AIRLINE_SEQ.NEXTVAL,
    s.NAME,
    s.IATA,
    s.COUNTRY,
    s.URL,
    s.TEAM
  );

-- ===== MERGE BATCH 3/5 =====
MERGE INTO TB_AIRLINE t
USING (
    SELECT 'HX' IATA, '홍콩 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'HY' IATA, '우즈베키스탄 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'HZ' IATA, '오로라' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'I2' IATA, '이베리아 익스프레스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'I3' IATA, 'ATA 이란 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'I4' IATA, '아일랜드 에어 익스프레스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'I7' IATA, '인디아원 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'I8' IATA, '이자비아' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'I9' IATA, '중국 중앙 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'IA' IATA, '이라크 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'IB' IATA, '이베리아 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'IC' IATA, '플라이 91' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'ID' IATA, '바틱 에어 인도네시아' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'IE' IATA, '솔로몬 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'IF' IATA, '플라이 바그다드' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'IH' IATA, '서던 스카이 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'II' IATA, 'IBC 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'IJ' IATA, '일본 춘추 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'IK' IATA, '에어 키리바시' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'IL' IATA, '트리가나 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'IM' IATA, '주피터 제트' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'IN' IATA, '남 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'IO' IATA, '이르에어로' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'IP' IATA, '펠리타 항공 서비스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'IQ' IATA, '카자흐 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'IR' IATA, '이란 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'IS' IATA, '세페란항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'IT' IATA, '타이거에어 타이완' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'IU' IATA, '슈퍼에어 제트' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'IV' IATA, 'GP 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'IW' IATA, '윙즈 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'IX' IATA, '에어 인디아 익스프레스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'IY' IATA, '예메니아' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'IZ' IATA, '앨키나 이스라엘 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'J0' IATA, '버팔로 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'J2' IATA, '아젤바이잔 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'J3' IATA, '노스웨스턴 에어 리스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'J4' IATA, '바드르 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'J5' IATA, '알래스카 시플레인서비스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'J6' IATA, '젯스마트 콜롬비아' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'J7' IATA, '아프리제트 비즈니스서비스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'J8' IATA, '버자야 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'J9' IATA, '자지라항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'JA' IATA, '제트스마트 칠레' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'JB' IATA, '헬리제트 인터내셔널' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'JC' IATA, '일본 항공 커뮤터' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'JD' IATA, '베이징 케피탈 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'JG' IATA, '장쑤 징동 화물항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'JH' IATA, '후지드림 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'JJ' IATA, '라탐 항공 브라질' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'JK' IATA, '에어카리베' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'JL' IATA, '일본 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'JM' IATA, '잠보제트' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'JN' IATA, '알래스카 항공 교통' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'JO' IATA, '조니카 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'JQ' IATA, '제트스타 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'JR' IATA, '조이 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'JS' IATA, '고려항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'JT' IATA, '라이온 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'JU' IATA, '에어 세르비아' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'JV' IATA, '베어스킨 항공사' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'JX' IATA, '스타룩스 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'JY' IATA, '인터 케르비안 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'JZ' IATA, '제트스마트 페루' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'K2' IATA, '에어리프트 알래스카' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'K3' IATA, '세이프 에어 컴퍼니' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'K4' IATA, 'ALS 리미티드' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'K6' IATA, '캄보디아 앙코르 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'K7' IATA, '밍갈라 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'K9' IATA, '칼리타 차터' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'KA' IATA, '에어로 노마드' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'KB' IATA, '드루크 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'KC' IATA, '에어 아스타나' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'KD' IATA, '웨스턴 글로벌 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'KE' IATA, '대한 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'KF' IATA, '에어 벨기에' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'KG' IATA, '키라임 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'KH' IATA, '알로하 항공 화물' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'KJ' IATA, '에어 인천' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'KK' IATA, 'LEAV 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'KL' IATA, 'KLM 네덜란드 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'KM' IATA, 'KM 몰타 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'KN' IATA, '차이나 유나이티드 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'KO' IATA, '알래스카 센트랄 익스프레스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'KP' IATA, '아스키 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'KQ' IATA, '케냐 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'KR' IATA, '캄보디아 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'KS' IATA, '에어 커넥트 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'KT' IATA, '에어아시아 캄보디아' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'KU' IATA, '쿠웨이트 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'KV' IATA, '크라스아비아' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'KW' IATA, '에어로스탄' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'KX' IATA, '케이맨 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'KY' IATA, '쿤밍 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'KZ' IATA, '일본 화물항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'L0' IATA, '릴라이언트 에어 차터' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'L2' IATA, '린든 항공화물' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'L3' IATA, 'DHL 과테말라' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'L5' IATA, '레드 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'L6' IATA, '모리타니 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'L7' IATA, '라탐 카고 콜롬비아' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'L8' IATA, '루루타이 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'L9' IATA, '루미윙스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'LA' IATA, '라탐 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'LB' IATA, '불 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'LC' IATA, '라 코스테나' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'LD' IATA, '에어 홍콩' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'LF' IATA, '컨투어 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'LG' IATA, '룩스에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'LH' IATA, '루프트한자' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'LJ' IATA, '진에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'LK' IATA, '라오스 스카이웨이' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'LM' IATA, '로간에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'LN' IATA, '리비아 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'LO' IATA, 'LOT 폴란드 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'LP' IATA, '라탐 항공 페루' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'LQ' IATA, '란메이 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'LR' IATA, '아비앙카 코스타리카' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'LS' IATA, '제트투컴' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'LT' IATA, '룽장 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'LU' IATA, '라탐 항공 칠레' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'LW' IATA, '라우다 유럽 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'LX' IATA, '스위스 국제 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'LY' IATA, '엘알 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'LZ' IATA, '에어 링크' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'M0' IATA, '에어로몽골' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'M2' IATA, 'MHS 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'M3' IATA, '라탐 카고 브라질' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'M4' IATA, '미스트랄 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'M5' IATA, '켄모어 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'M6' IATA, '아메리제트 인터내셔널' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'M7' IATA, '마스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'M8' IATA, '스카이제트 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'MB' IATA, 'MNG 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'MD' IATA, '마다가스카르 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'ME' IATA, '미들 이스트 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'MF' IATA, '샤먼 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'MG' IATA, '이즈니스 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'MH' IATA, '말레이시아 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'MI' IATA, '프리버드 유럽' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'MJ' IATA, '마이웨이 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'MK' IATA, '에어 모리셔스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'ML' IATA, '스카이 말리' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'MM' IATA, '피치 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'MO' IATA, '캄 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'MP' IATA, '마르틴에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'MQ' IATA, '엔보이' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'MR' IATA, '훈누 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'MS' IATA, '이집트항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'MT' IATA, '몰타 메드에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'MU' IATA, '중국 동방 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'MV' IATA, '에어 메디티라아난' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'MW' IATA, '몰타 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'MX' IATA, '브리즈 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'MZ' IATA, '아마쿠사 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'N0' IATA, '노르스 애틀랜틱 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'N2' IATA, '에어로 콘트렉트 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'N3' IATA, '볼라리스 엘살바도르' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'N4' IATA, '노드윈드 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'N5' IATA, '메다비아' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'N6' IATA, '에어 원나인' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'N7' IATA, '노르딕 리저널 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'N8' IATA, '내셔널 미국 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'N9' IATA, '슈리 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'NB' IATA, '버니크 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'NC' IATA, '노던 에어 카고' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'ND' IATA, '노르디카' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'NE' IATA, '네스마 이집트 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'NF' IATA, '에어 바누아투' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'NG' IATA, '노바 항공 아르메니아' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'NH' IATA, '전일본공수' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'NI' IATA, '포튜갈리아 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'NJ' IATA, '나제르 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'NK' IATA, '스피릿 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'NL' IATA, '에어로4M' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'NM' IATA, '나티레바 에어 모아나' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'NO' IATA, '네오스 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'NP' IATA, '나일 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'NQ' IATA, '에어재팬' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'NR' IATA, '만타 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'NS' IATA, '허베이 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'NT' IATA, '빈터 카나리아스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'NU' IATA, '저팬 트랜스오션 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'NV' IATA, '카룬 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'NX' IATA, '에어 마카오' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'NY' IATA, '에어 아이슬란드 커넥트' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'NZ' IATA, '에어 뉴질랜드' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'O3' IATA, 'SF 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'O4' IATA, '안데스리네아스애리아' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'O7' IATA, '오렌부르크 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'O8' IATA, '마라톤 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'O9' IATA, '노바 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'OA' IATA, '올림픽 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'OB' IATA, '볼리비아 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'OC' IATA, '오리엔탈 에어 브리지' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'OD' IATA, '바틱 에어 말레이시아' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'OF' IATA, '오버랜드 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'OG' IATA, '플레이 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'OH' IATA, 'PSA 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'OI' IATA, '힌터렌드 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
) s
ON (t.AIRLINE_IATA_CODE = s.IATA)
WHEN NOT MATCHED THEN
  INSERT (
    AIRLINE_ID,
    AIRLINE_AIRLINE_NAME,
    AIRLINE_IATA_CODE,
    AIRLINE_COUNTRY,
    AIRLINE_URL,
    AIRPORT_TEAM
  )
  VALUES (
    TB_AIRLINE_SEQ.NEXTVAL,
    s.NAME,
    s.IATA,
    s.COUNTRY,
    s.URL,
    s.TEAM
  );

-- ===== MERGE BATCH 4/5 =====
MERGE INTO TB_AIRLINE t
USING (
    SELECT 'OJ' IATA, '닉스 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'OL' IATA, '사모아 에어웨이' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'OM' IATA, 'MIAT 몽골 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'ON' IATA, '나우루 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'OO' IATA, '스카이웨스트 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'OP' IATA, '패션에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'OQ' IATA, '충칭 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'OR' IATA, 'TUI 플라이 네덜란드' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'OS' IATA, '오스트리안 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'OU' IATA, '크로아티아 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'OV' IATA, '살람 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'OW' IATA, '스카이워드 익스프레스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'OX' IATA, '원항공 SAU' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'OY' IATA, '옴니 에어 인터네셔널' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'OZ' IATA, '아시아나 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'P0' IATA, '프로플라이트 잠비아' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'P2' IATA, '에어케냐' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'P4' IATA, '에어 피스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'P5' IATA, '코파 항공 콜롬비아' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'P6' IATA, '파스칸 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'P8' IATA, '스프린트 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'P9' IATA, '아시아 태평양 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'PA' IATA, '에어블루' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'PB' IATA, 'PAL 항공 캐나다' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'PC' IATA, '페가수스 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'PD' IATA, '포터 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'PE' IATA, '피폴즈 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'PF' IATA, '에어시알' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'PG' IATA, '방콕항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'PH' IATA, 'ASL 오스트레일리아 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'PI' IATA, '폴라 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'PJ' IATA, '에어 생피에르' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'PK' IATA, '파키스탄 국제항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'PL' IATA, '서던에어 차터' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'PM' IATA, '카나리플라이 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'PN' IATA, '웨스트 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'PO' IATA, '폴라 에어 카고' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'PQ' IATA, '스카이업' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'PR' IATA, '필리핀 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'PT' IATA, '피드 몬트 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'PU' IATA, '플러스 울트라 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'PV' IATA, '세인트바스 커뮤터' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'PW' IATA, '프리시즌 항공서비스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'PX' IATA, '에어 뉴기니' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'PY' IATA, '수리남 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'PZ' IATA, '라탐 항공 파라과이' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'Q2' IATA, '몰디비안' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'Q3' IATA, '앙구일라 에어서비스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'Q4' IATA, '유로 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'Q5' IATA, '40 마일 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'Q6' IATA, '볼라리스 코스타리카' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'Q7' IATA, 'DHL 에어 오스트리아' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'Q8' IATA, '트랜스에어 콩고' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'Q9' IATA, '그린아프리카 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'QA' IATA, '퀸 빌키스 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'QB' IATA, '케심 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'QC' IATA, '카메룬 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'QD' IATA, 'JC 캄보디아 국제항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'QE' IATA, '익스프레스 프레이터스 오스트랄리아' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'QF' IATA, '콴타스 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'QG' IATA, '시티링크' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'QH' IATA, '뱀부 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'QI' IATA, '이봄에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'QK' IATA, '재즈 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'QL' IATA, '레이저' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'QN' IATA, '스카이트랜스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'QO' IATA, '퀵젯 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'QP' IATA, '아카사 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'QQ' IATA, '알리앙스 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'QR' IATA, '카타르 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'QS' IATA, '스마트윙스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'QT' IATA, '아비앙카 카고' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'QU' IATA, '스카이라인 익스프레스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'QV' IATA, '라오스 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'QW' IATA, '칭다오 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'QX' IATA, '호라이즌 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'QY' IATA, '유럽 항공 운송 라이프찌히' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'QZ' IATA, '인도네시아 에어아시아' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'R0' IATA, '루스키 에어로 인도네시아' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'R2' IATA, '트랜스에어 세네갈' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'R3' IATA, '야쿠티아 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'R4' IATA, '라노 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'R5' IATA, '요르단 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'R6' IATA, '도트 LT' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'R7' IATA, '세븐에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'R8' IATA, '선댄스 항공 베네수엘라' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'RA' IATA, '네팔 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'RB' IATA, '시리아 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'RC' IATA, '아틀랜틱 에어웨이' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'RD' IATA, '이지 차터' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'RE' IATA, '에어허버항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'RF' IATA, '에어로 K' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'RG' IATA, '로타나 제트 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'RH' IATA, '홍콩 화물항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'RI' IATA, '림분 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'RJ' IATA, '로얄 요르단 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'RK' IATA, '라이언에어 영국' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'RM' IATA, '에어 딜리얀스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'RO' IATA, 'TAROM 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'RP' IATA, '부다페스트 에어크래프트 서비스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'RQ' IATA, '캄 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'RR' IATA, '버즈' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'RS' IATA, '에어 서울' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'RT' IATA, 'UVT 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'RV' IATA, '에어 캐나다 루즈' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'RW' IATA, '로얄 에어 필리핀' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'RY' IATA, '장시 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'RZ' IATA, 'SANSA 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'S0' IATA, 'SOSA 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'S4' IATA, '아조레스 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'S5' IATA, '스타 에어 인도' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'S6' IATA, '선라이즈 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'S7' IATA, 'S7 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'S8' IATA, '스카이 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'S9' IATA, '플라이 빅' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'SA' IATA, '남아프리카 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'SB' IATA, '에어칼린' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'SC' IATA, '산동 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'SD' IATA, '수단 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'SE' IATA, '유럽 화물항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'SF' IATA, '타실리 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'SG' IATA, '스파이스 제트' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'SH' IATA, '샤프 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'SI' IATA, '블루 아일랜드' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'SJ' IATA, '수르위자야 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'SK' IATA, 'SAS 랑공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'SL' IATA, 'SAS 연결' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'SM' IATA, '에어카이로' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'SN' IATA, '브뤼셀 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'SO' IATA, '살사 다아이티' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'SP' IATA, 'SATA 에어 아조레스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'SQ' IATA, '싱가포르 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'SR' IATA, '스카이웨어 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'SS' IATA, '코르스에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'ST' IATA, '에어탈루인' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'SU' IATA, '아에로플로트' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'SV' IATA, '사우디아 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'SX' IATA, '플라이 GTA 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'SY' IATA, '선 컨트리 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'SZ' IATA, '소몬에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'T0' IATA, 'TACA 페루' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'T2' IATA, '나키나 에어 서비스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'T3' IATA, '이스턴 에어웨이' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'T5' IATA, '투르크메니스탄 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'T6' IATA, '에어스위프트' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'T7' IATA, '트랜스카르가 국제항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'T9' IATA, '투르피알 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'TA' IATA, '아비앙카 엘살바도르' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'TB' IATA, 'TUI 플라이 벨기에' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'TC' IATA, '에어 탄자니아' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'TD' IATA, '트빌리시 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'TE' IATA, '스카이택시' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'TG' IATA, '타이 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'TH' IATA, '라야 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'TI' IATA, '테일윈드 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'TJ' IATA, '트레이드윈드 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'TK' IATA, '터키 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'TL' IATA, '에어노스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'TM' IATA, '람 모잠비크 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'TN' IATA, '에어 타히티 누이' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'TO' IATA, '트랜스아비아 프랑스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'TP' IATA, 'TAP 항공 포르투갈' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'TR' IATA, '스쿳' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'TS' IATA, '에어 트란삿' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'TT' IATA, '브라텐스 국제항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'TU' IATA, '튀니지 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'TV' IATA, '티베트 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'TW' IATA, '티웨이 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'TX' IATA, '에어 카라이브' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'TY' IATA, '에어 칼레도니' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'TZ' IATA, '에어 앙카' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'U2' IATA, '이지젯' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'U3' IATA, '스카이게이트 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'U4' IATA, '부다 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'U5' IATA, '스카이업 MT' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'U6' IATA, '우랄 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'U7' IATA, '유니월드에어카고' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'U8' IATA, '투스 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'UA' IATA, '유나이티드 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'UB' IATA, '미얀마 국영항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'UC' IATA, '라탐 카고 칠레' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'UD' IATA, 'UR 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'UE' IATA, '얼티밋 에어 셔틀' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'UF' IATA, '페트롤리움 에어 서비스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'UG' IATA, '튀니지 항공 익스프레스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'UI' IATA, '오릭스 에어서비스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'UJ' IATA, '알마스리아 유니버셜 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'UL' IATA, '스리랑카 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'UM' IATA, '에어 짐바브웨' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'UO' IATA, '홍콩 익스프레스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'UP' IATA, '바하마항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'UQ' IATA, '우루무치 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'UR' IATA, '우간다 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'US' IATA, '실크 아비아' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'UT' IATA, '유테어 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'UU' IATA, '에어 오스트랄' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'UX' IATA, '에어 유로파 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'UZ' IATA, '부라키 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'V0' IATA, '콘비아사' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'V3' IATA, '카르파트에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
) s
ON (t.AIRLINE_IATA_CODE = s.IATA)
WHEN NOT MATCHED THEN
  INSERT (
    AIRLINE_ID,
    AIRLINE_AIRLINE_NAME,
    AIRLINE_IATA_CODE,
    AIRLINE_COUNTRY,
    AIRLINE_URL,
    AIRPORT_TEAM
  )
  VALUES (
    TB_AIRLINE_SEQ.NEXTVAL,
    s.NAME,
    s.IATA,
    s.COUNTRY,
    s.URL,
    s.TEAM
  );

-- ===== MERGE BATCH 5/5 =====
MERGE INTO TB_AIRLINE t
USING (
    SELECT 'V4' IATA, '벤세카 인터내셔널' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'V5' IATA, '에어로비아스 DAP' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'V6' IATA, 'VI 에어링크' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'V7' IATA, '볼로테아' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'V8' IATA, '아트란' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'V9' IATA, '밴에어 유럽' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'VA' IATA, '버진 오스트레일리아' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'VB' IATA, '비바 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'VC' IATA, '알류샨 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'VE' IATA, '클릭 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'VF' IATA, '에이젯' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'VI' IATA, '볼가-드뇌프르 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'VJ' IATA, '비엣젯 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'VK' IATA, '밸류제트' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'VL' IATA, '루프트한자 시티 에어라인즈' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'VM' IATA, '맥스 항공 나이지리아' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'VN' IATA, '베트남 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'VP' IATA, '빌라에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'VQ' IATA, '노보에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'VR' IATA, '카페베르데 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'VS' IATA, '버진 애틀랜틱 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'VT' IATA, '에어 타히티' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'VU' IATA, '비엣트래블 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'VY' IATA, '부엘링 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'VZ' IATA, '타이 비엣젯 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'W2' IATA, '플렉스플라이트' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'W3' IATA, '아리크 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'W4' IATA, '위즈 에어 몰타' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'W5' IATA, '마한 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'W6' IATA, '위즈 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'W8' IATA, '카고제트 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'W9' IATA, '위즈 에어 영국' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'WA' IATA, 'KLM 시티호퍼' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'WB' IATA, '르완다 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'WC' IATA, '아비앙카 온두라스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'WD' IATA, '모던 로지스틱스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'WF' IATA, '위데뢰에 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'WG' IATA, '선윙 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'WH' IATA, '윙고 파나마' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'WI' IATA, '화이트항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'WJ' IATA, '제트스마트 아르헨티나' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'WK' IATA, '에델바이스 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'WL' IATA, '월드 아틀랜틱 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'WM' IATA, '윈에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'WN' IATA, '사우스웨스트 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'WP' IATA, '와사야 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'WR' IATA, '웨스트제트 앙코르' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'WS' IATA, '웨스트제트' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'WT' IATA, '스위프트에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'WU' IATA, '웨스턴 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'WV' IATA, '플라이 나미비아' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'WW' IATA, 'M 제트 인터내셔널' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'WX' IATA, '시티제트' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'WY' IATA, '오만 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'WZ' IATA, '레더윙즈' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'X3' IATA, 'TUI 플라이' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'X5' IATA, '에어 유로파 익스프레스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'X7' IATA, '챌린지 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'X8' IATA, '에어맥스 카고' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'X9' IATA, '아비온 익스프레스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'XC' IATA, '코렌돈 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'XE' IATA, 'JSX 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'XF' IATA, '몽골 화물항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'XJ' IATA, '타이 에어아시아 X' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'XK' IATA, '에어 코시카' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'XL' IATA, '라탐 항공 에콰도르' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'XM' IATA, '지멕스 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'XO' IATA, '씨에어 인터내셔널' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'XP' IATA, '아벨로항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'XQ' IATA, '썬익스프레스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'XR' IATA, '코렌돈 항공 유럽' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'XU' IATA, '아프리카 익스프레스 에어웨이' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'XY' IATA, '플라이 나스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'XZ' IATA, '에어리탈리아' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'Y2' IATA, '에어 센츄리' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'Y3' IATA, '스페이스비 에어라인즈' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'Y4' IATA, '볼라리스 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'Y5' IATA, '헤이웨이즈항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'Y6' IATA, 'AB 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'Y7' IATA, '노드스타 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'Y8' IATA, '수파르나 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'YB' IATA, '하버 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'YC' IATA, '야말 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'YD' IATA, '에어 시에라리온' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'YE' IATA, '야 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'YG' IATA, 'YTO 화물항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'YH' IATA, '선스플래시 항공 LLC' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'YI' IATA, '오야 국제항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'YJ' IATA, 'AMC 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'YK' IATA, '아비아 트래픽 컴퍼니' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'YL' IATA, '리비아 윙스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'YN' IATA, '에어 크리벡' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'YP' IATA, '에어 프레미아' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'YQ' IATA, 'TAR 멕시코' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'YR' IATA, '그랜드캐년 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'YS' IATA, '플라이트 링크' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'YT' IATA, '예티 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'YU' IATA, '유로 애틀랜틱 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'YV' IATA, '메사 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'YW' IATA, '이베리아 지역 항공 노스트룸' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'YX' IATA, '리퍼블릭 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'Z0' IATA, '노르스 애틀랜틱 영국' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'Z2' IATA, '필리핀 에어아시아' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'Z3' IATA, '타나나 에어서비스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'Z4' IATA, '푸마 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'Z7' IATA, '카멕스항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'ZA' IATA, '스카이 앙코르 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'ZB' IATA, '에어 알바니아' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'ZD' IATA, '에와 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'ZE' IATA, '이스타항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'ZF' IATA, '아주르 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'ZG' IATA, '집 에어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'ZH' IATA, '선전 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'ZK' IATA, '제트 아비아' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'ZL' IATA, '렉스 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'ZM' IATA, '에어 마냐스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'ZN' IATA, '잠비아 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'ZO' IATA, '줌 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'ZP' IATA, '파라네어' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'ZQ' IATA, '독일 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'ZR' IATA, '아비아콘지오트랜스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'ZT' IATA, '타이탄 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'ZU' IATA, '에티오피아 모잠비크 항공' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'ZV' IATA, '에어루스' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
    UNION ALL
    SELECT 'ZW' IATA, '에어 위스콘신' NAME, 'UNKNOWN' COUNTRY, NULL URL, NULL TEAM FROM dual
) s
ON (t.AIRLINE_IATA_CODE = s.IATA)
WHEN NOT MATCHED THEN
  INSERT (
    AIRLINE_ID,
    AIRLINE_AIRLINE_NAME,
    AIRLINE_IATA_CODE,
    AIRLINE_COUNTRY,
    AIRLINE_URL,
    AIRPORT_TEAM
  )
  VALUES (
    TB_AIRLINE_SEQ.NEXTVAL,
    s.NAME,
    s.IATA,
    s.COUNTRY,
    s.URL,
    s.TEAM
  );

COMMIT;
